Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2019-10, with the labels that each got.

#3 Groups caching support
  Makefile
  google_oslogin_control
  packaging/setup_deb.sh
  packaging/setup_rpm.sh
  src/Makefile
  src/authorized_keys/authorized_keys.cc
  src/cache_refresh/cache_refresh.cc
  src/include/compat.h
  src/include/nss_cache_oslogin.h
  src/include/oslogin_utils.h
  src/nss/nss_cache_oslogin.c
  src/nss/nss_oslogin.cc
  src/oslogin_utils.cc
  src/pam/pam_oslogin_login.cc
  test/Makefile
  test/oslogin_utils_test.cc
Labels: approved, size/XXL

#9 Packaging scripts
  packaging/build_deb.sh
  packaging/build_packages_wf.json
  packaging/build_rpm.sh
  packaging/common.sh
  packaging/daisy_startupscript_deb.sh
  packaging/daisy_startupscript_rpm.sh
  packaging/debian/changelog
  src/Makefile
  src/cache_refresh/cache_refresh.cc
Labels: approved, lgtm, size/L

#10 Correct JSON refcount decrementing (again)
  src/oslogin_utils.cc
Labels: approved, lgtm, size/XS

#11 Keep SRPMs; bump version
  packaging/common.sh
  packaging/daisy_startupscript_rpm.sh
  packaging/debian/changelog
  src/Makefile
Labels: approved, lgtm, size/S

#12 Fix endgrent funtion name for FreeBSD
  src/nss/nss_cache_oslogin.c
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
