Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2020-01, with the labels that each got.

#23 Systemd timer
  90-google-compute-engine-oslogin.preset
  google-oslogin-cache.service
  google-oslogin-cache.timer
  packaging/debian/rules
  packaging/google-compute-engine-oslogin.spec
  src/Makefile
Labels: approved, cla: yes, lgtm, size/M

#20 - Add license file, code license under Apache-v2
  LICENSE
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#25 add junit
  Makefile
  test/Makefile
Labels: approved, cla: yes, lgtm, size/XS

#24 continue on error
  src/cache_refresh/cache_refresh.cc
  src/google_authorized_keys
  src/google_oslogin_nss_cache
  src/oslogin_utils.cc
  test/oslogin_utils_test.cc
Labels: approved, cla: yes, lgtm, size/L
