Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2020-09, with the labels that each got.

#40 Add new NSS module
  src/nss/new_nss_oslogin.c
  test/Makefile
  test/oslogin_test.cc
Labels: approved, cla: yes, size/L

#41 add dial and recvline
  src/nss/new_nss_oslogin.c
Labels: approved, cla: yes, lgtm, size/M

#44 Change requires to not require the python library for policycoreutils.
  packaging/google-compute-engine-oslogin.spec
Labels: approved, lgtm, size/S

#42 add getpwnam,getpwuid,getgrnam,getgrgid
  src/nss/new_nss_oslogin.c
  test/Makefile
  test/oslogin_test.cc
Labels: approved, cla: yes, lgtm, size/L
