Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2021-07, with the labels that each got.

#63 Use IP address for calling the metadata server.
  src/include/oslogin_utils.h
  test/Makefile
  test/oslogin_utils_test.cc
Labels: approved, cla: yes, lgtm, size/S

#64 throw exceptions in cache_refresh
  src/cache_refresh/cache_refresh.cc
Labels: approved, cla: yes, lgtm, size/M

#65 JSON object cleanup
  src/nss/nss_cache_oslogin.c
  src/nss/nss_oslogin.cc
  src/oslogin_utils.cc
Labels: approved, cla: yes, lgtm, size/L
