Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2023-08, with the labels that each got.

#106 byoid: extract and apply the ca fingerprint to policy call
  .gitignore
  src/Makefile
  src/include/oslogin_sshca.h
  src/pam/oslogin_sshca.cc
  src/pam/pam_oslogin_admin.cc
  src/pam/pam_oslogin_login.cc
  test/Makefile
  test/oslogin_sshca_test.cc
  third_party/include/openbsd.h
Labels: size/XL, lgtm, approved

#110 Update owners.
  OWNERS
Labels: lgtm, size/XS, approved

#109 sshca: support method token and handle multi line
  src/pam/oslogin_sshca.cc
  test/Makefile
  test/oslogin_sshca_test.cc
Labels: lgtm, approved, size/L

#111 sshca: add tests with fingerprint and multiple extensions
  test/oslogin_sshca_test.cc
Labels: lgtm, approved, size/M

#113 selinux: add sshd_key_t type enforcement to trusted user ca
  selinux/oslogin.fc
  selinux/oslogin.pp
  selinux/oslogin.te
Labels: lgtm, size/XS, approved

#114 selinux: fix selinux build
  .gitignore
  Makefile
  packaging/google-compute-engine-oslogin.spec
  selinux/oslogin.pp
Labels: size/S, lgtm, approved
