Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2023-11, with the labels that each got.

#121 Update owners.
  OWNERS
Labels: lgtm, size/XS, approved

#122 build: fix clang build
  src/Makefile
Labels: lgtm, size/XS, approved, ok-to-test

#124 build: fix DESTDIR concatenation
  src/Makefile
Labels: lgtm, approved, size/M
