Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2024-12, with the labels that each got.

#149 Fix a bug where very large GIDs would cause integer overflow errors
  src/Makefile
  src/include/oslogin_utils.h
  src/oslogin_utils.cc
  test/Makefile
  test/oslogin_sshca_test.cc
  test/oslogin_test.cc
  test/oslogin_utils_test.cc
Labels: size/S, lgtm, approved, ok-to-test

#151 Fix base64.h's missing includes and BSD types
  src/openbsd-compat/base64.h
Labels: size/S, lgtm, approved

#152 Apply "include what you use," fixing missing include statements broadly.
  src/authorized_keys/authorized_keys.cc
  src/authorized_keys/authorized_keys_sk.cc
  src/authorized_principals/authorized_principals.cc
  src/cache_refresh/cache_refresh.cc
  src/include/compat.h
  src/include/nss_cache_oslogin.h
  src/nss/nss_cache_oslogin.c
  src/nss/nss_oslogin.cc
  src/oslogin_sshca.cc
  src/oslogin_utils.cc
  src/pam/pam_oslogin_admin.cc
  src/pam/pam_oslogin_login.cc
Labels: lgtm, approved, size/M

#150 Fix bad struct initialization pattern `= { 0 }`
  src/authorized_keys/authorized_keys.cc
  src/authorized_keys/authorized_keys_sk.cc
  src/authorized_principals/authorized_principals.cc
  src/pam/pam_oslogin_admin.cc
  src/pam/pam_oslogin_login.cc
Labels: size/S, lgtm, approved, ok-to-test

#155 Delete new_nss_oslogin.c, which was never actually used.
  src/nss/new_nss_oslogin.c
  test/Makefile
  test/oslogin_test.cc
Labels: size/XL, lgtm, approved

#157 Add Eric to the owners file.
  OWNERS
Labels: lgtm, size/XS, approved

#158 Send the correct type to SysLogErr to make the clang sanitizer happy.
  src/oslogin_utils.cc
Labels: lgtm, size/XS, approved
