Repository GoogleCloudPlatform/guest-oslogin, pull requests merged in 2024-11, with the labels that each got.

#135 Log an error when user has no challenges configured
  src/pam/pam_oslogin_login.cc
Labels: lgtm, size/XS, approved, ok-to-test

#144 OS Login agent searches for full fingerprint extension instead of equals
  src/oslogin_sshca
  src/oslogin_sshca.cc
  test/oslogin_sshca_test.cc
Labels: lgtm, approved, size/M

#146 Minor cleanup: Delete oslogin_sshca binary, add it to the ignore list
  .gitignore
  src/oslogin_sshca
Labels: lgtm, size/XS, approved

#147 Follow the Google style guide by using the "local include style" to include files from this project.
  src/Makefile
  src/authorized_keys/authorized_keys.cc
  src/authorized_keys/authorized_keys_sk.cc
  src/authorized_principals/authorized_principals.cc
  src/cache_refresh/cache_refresh.cc
  src/include/oslogin_sshca.h
  src/nss/nss_cache_oslogin.c
  src/nss/nss_oslogin.cc
  src/oslogin_sshca.cc
  src/oslogin_utils.cc
  src/pam/pam_oslogin_admin.cc
  src/pam/pam_oslogin_login.cc
Labels: lgtm, approved, ok-to-test, size/M

#148 Rename openbsd.h to base64.h and move it into the src/ folder
  src/Makefile
  src/openbsd-compat/base64.h
  src/oslogin_sshca.cc
Labels: lgtm, size/XS, approved, ok-to-test
